apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: flask-health-check-prod

namespace: production

resources:
- ../../base

patches:
- path: resource-patch.yaml
  target:
    kind: Deployment
    name: flask-health-check

images:
- name: ghcr.io/your-username/flask-health-check
  newTag: latest
