apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: flask-health-check

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: ghcr.io/michigety/flask_gitops_argocd
  newTag: 0.0.1
